package net.minecraft.client.render.entity.model;

import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.block.WoodType;
import net.minecraft.client.model.Dilation;
import net.minecraft.client.model.TexturedModelData;
import net.minecraft.client.render.block.entity.BedBlockEntityRenderer;
import net.minecraft.client.render.block.entity.ConduitBlockEntityRenderer;
import net.minecraft.client.render.block.entity.DecoratedPotBlockEntityRenderer;
import net.minecraft.client.render.block.entity.HangingSignBlockEntityRenderer;
import net.minecraft.client.render.block.entity.SignBlockEntityRenderer;
import net.minecraft.client.render.block.entity.model.BannerBlockModel;
import net.minecraft.client.render.block.entity.model.BannerFlagBlockModel;
import net.minecraft.client.render.block.entity.model.BellBlockModel;
import net.minecraft.client.render.block.entity.model.ChestBlockModel;
import net.minecraft.client.render.entity.DragonEntityModel;
import net.minecraft.client.render.entity.WitherSkullEntityRenderer;

@Environment(EnvType.CLIENT)
public class EntityModels {
	private static final Dilation FISH_PATTERN_DILATION = new Dilation(0.008F);
	private static final Dilation ARMOR_DILATION = new Dilation(1.0F);
	private static final Dilation HAT_DILATION = new Dilation(0.5F);

	public static Map<EntityModelLayer, TexturedModelData> getModels() {
		Builder<EntityModelLayer, TexturedModelData> builder = ImmutableMap.builder();
		TexturedModelData texturedModelData = TexturedModelData.of(BipedEntityModel.getModelData(Dilation.NONE, 0.0F), 64, 64);
		EquipmentModelData<TexturedModelData> equipmentModelData = BipedEntityModel.createEquipmentModelData(HAT_DILATION, ARMOR_DILATION)
			.map(data -> TexturedModelData.of(data, 64, 32));
		EquipmentModelData<TexturedModelData> equipmentModelData2 = equipmentModelData.map(modelData -> modelData.transform(BipedEntityModel.BABY_TRANSFORMER));
		EquipmentModelData<TexturedModelData> equipmentModelData3 = PlayerEntityModel.createEquipmentModelData(HAT_DILATION, ARMOR_DILATION)
			.map(data -> TexturedModelData.of(data, 64, 32));
		EquipmentModelData<TexturedModelData> equipmentModelData4 = PiglinEntityModel.createEquipmentModelData(HAT_DILATION, new Dilation(1.02F))
			.map(data -> TexturedModelData.of(data, 64, 32));
		EquipmentModelData<TexturedModelData> equipmentModelData5 = equipmentModelData4.map(modelData -> modelData.transform(BipedEntityModel.BABY_TRANSFORMER));
		TexturedModelData texturedModelData2 = MinecartEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData3 = SkullEntityModel.getSkullTexturedModelData();
		TexturedModelData texturedModelData4 = TexturedModelData.of(AbstractHorseEntityModel.getModelData(Dilation.NONE), 64, 64);
		TexturedModelData texturedModelData5 = TexturedModelData.of(AbstractHorseEntityModel.getBabyHorseModelData(Dilation.NONE), 64, 64);
		TexturedModelData texturedModelData6 = HorseSaddleEntityModel.getTexturedModelData(false);
		TexturedModelData texturedModelData7 = HorseSaddleEntityModel.getTexturedModelData(true);
		ModelTransformer modelTransformer = ModelTransformer.scaling(0.9375F);
		TexturedModelData texturedModelData8 = IllagerEntityModel.getTexturedModelData().transform(modelTransformer);
		TexturedModelData texturedModelData9 = AxolotlEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData10 = BeeEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData11 = CowEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData12 = ColdChickenEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData13 = ColdCowEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData14 = ColdPigEntityModel.getTexturedModelData(Dilation.NONE);
		TexturedModelData texturedModelData15 = ElytraEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData16 = TexturedModelData.of(FelineEntityModel.getModelData(Dilation.NONE), 64, 32);
		TexturedModelData texturedModelData17 = texturedModelData16.transform(FelineEntityModel.BABY_TRANSFORMER);
		TexturedModelData texturedModelData18 = TexturedModelData.of(FelineEntityModel.getModelData(new Dilation(0.01F)), 64, 32);
		TexturedModelData texturedModelData19 = TexturedModelData.of(PiglinEntityModel.getModelData(Dilation.NONE), 64, 64);
		TexturedModelData texturedModelData20 = TexturedModelData.of(PiglinHeadEntityModel.getModelData(), 64, 64);
		TexturedModelData texturedModelData21 = SkullEntityModel.getHeadTexturedModelData();
		TexturedModelData texturedModelData22 = LlamaEntityModel.getTexturedModelData(Dilation.NONE);
		TexturedModelData texturedModelData23 = LlamaEntityModel.getTexturedModelData(new Dilation(0.5F));
		TexturedModelData texturedModelData24 = StriderEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData25 = HoglinEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData26 = HoglinEntityModel.getBabyTexturedModelData();
		TexturedModelData texturedModelData27 = SkeletonEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData28 = TexturedModelData.of(VillagerResemblingModel.getModelData(), 64, 64).transform(modelTransformer);
		TexturedModelData texturedModelData29 = TexturedModelData.of(VillagerResemblingModel.getNoHatModelData(), 64, 64).transform(modelTransformer);
		TexturedModelData texturedModelData30 = SpiderEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData31 = ArmadilloEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData32 = CamelEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData33 = CamelSaddleEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData34 = ChickenEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData35 = GoatEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData36 = PandaEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData37 = PigEntityModel.getTexturedModelData(Dilation.NONE);
		TexturedModelData texturedModelData38 = PigEntityModel.getTexturedModelData(new Dilation(0.5F));
		TexturedModelData texturedModelData39 = SheepEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData40 = SheepWoolEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData41 = SnifferEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData42 = TurtleEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData43 = WarmCowEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData44 = TexturedModelData.of(WolfEntityModel.getTexturedModelData(Dilation.NONE), 64, 32);
		TexturedModelData texturedModelData45 = TexturedModelData.of(WolfEntityModel.getTexturedModelData(new Dilation(0.2F)), 64, 32);
		TexturedModelData texturedModelData46 = ZombieVillagerEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData47 = ZombieVillagerEntityModel.getTexturedModelDataWithoutHead();
		TexturedModelData texturedModelData48 = ArmorStandEntityModel.getTexturedModelData();
		EquipmentModelData<TexturedModelData> equipmentModelData6 = ArmorStandArmorEntityModel.getEquipmentModelData(HAT_DILATION, ARMOR_DILATION);
		TexturedModelData texturedModelData49 = DrownedEntityModel.getTexturedModelData(Dilation.NONE);
		TexturedModelData texturedModelData50 = DrownedEntityModel.getTexturedModelData(new Dilation(0.25F));
		TexturedModelData texturedModelData51 = SquidEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData52 = DolphinEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData53 = SalmonEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData54 = NautilusSaddleEntityModel.getTexturedModelData();
		builder.put(EntityModelLayers.ALLAY, AllayEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.ARMADILLO, texturedModelData31);
		builder.put(EntityModelLayers.ARMADILLO_BABY, texturedModelData31.transform(ArmadilloEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.ARMOR_STAND, texturedModelData48);
		EntityModelLayers.ARMOR_STAND_EQUIPMENT.addTo(equipmentModelData6, builder);
		builder.put(EntityModelLayers.ARMOR_STAND_SMALL, texturedModelData48.transform(BipedEntityModel.BABY_TRANSFORMER));
		EntityModelLayers.SMALL_ARMOR_STAND_EQUIPMENT.addTo(equipmentModelData6.map(modelData -> modelData.transform(BipedEntityModel.BABY_TRANSFORMER)), builder);
		builder.put(EntityModelLayers.ARROW, ArrowEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.AXOLOTL, texturedModelData9);
		builder.put(EntityModelLayers.AXOLOTL_BABY, texturedModelData9.transform(AxolotlEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.STANDING_BANNER, BannerBlockModel.getTexturedModelData(true));
		builder.put(EntityModelLayers.WALL_BANNER, BannerBlockModel.getTexturedModelData(false));
		builder.put(EntityModelLayers.STANDING_BANNER_FLAG, BannerFlagBlockModel.getTexturedModelData(true));
		builder.put(EntityModelLayers.WALL_BANNER_FLAG, BannerFlagBlockModel.getTexturedModelData(false));
		builder.put(EntityModelLayers.BAT, BatEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.BED_FOOT, BedBlockEntityRenderer.getFootTexturedModelData());
		builder.put(EntityModelLayers.BED_HEAD, BedBlockEntityRenderer.getHeadTexturedModelData());
		builder.put(EntityModelLayers.BEE, texturedModelData10);
		builder.put(EntityModelLayers.BEE_BABY, texturedModelData10.transform(BeeEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.BEE_STINGER, StingerModel.getTexturedModelData());
		builder.put(EntityModelLayers.BELL, BellBlockModel.getTexturedModelData());
		builder.put(EntityModelLayers.BLAZE, BlazeEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.BOAT, BoatEntityModel.getBaseTexturedModelData());
		builder.put(EntityModelLayers.BOGGED, BoggedEntityModel.getTexturedModelData());
		EntityModelLayers.BOGGED_EQUIPMENT.addTo(equipmentModelData, builder);
		builder.put(EntityModelLayers.BOGGED_OUTER, TexturedModelData.of(BipedEntityModel.getModelData(new Dilation(0.2F), 0.0F), 64, 32));
		builder.put(EntityModelLayers.BOOK, BookModel.getTexturedModelData());
		builder.put(EntityModelLayers.BREEZE, BreezeEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.BREEZE_WIND, BreezeEntityModel.getWindTexturedModelData());
		builder.put(EntityModelLayers.BREEZE_EYES, BreezeEntityModel.getEyesTexturedModelData());
		builder.put(EntityModelLayers.CAT, texturedModelData16.transform(CatEntityModel.CAT_TRANSFORMER));
		builder.put(EntityModelLayers.CAT_BABY, texturedModelData17.transform(CatEntityModel.CAT_TRANSFORMER));
		builder.put(EntityModelLayers.CAT_COLLAR, texturedModelData18.transform(CatEntityModel.CAT_TRANSFORMER));
		builder.put(EntityModelLayers.CAT_BABY_COLLAR, texturedModelData18.transform(FelineEntityModel.BABY_TRANSFORMER).transform(CatEntityModel.CAT_TRANSFORMER));
		builder.put(EntityModelLayers.CAMEL, texturedModelData32);
		builder.put(EntityModelLayers.CAMEL_BABY, texturedModelData32.transform(CamelEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.CAMEL_SADDLE, texturedModelData33);
		builder.put(EntityModelLayers.CAMEL_BABY_SADDLE, texturedModelData33.transform(CamelEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.CAMEL_HUSK, texturedModelData33);
		builder.put(EntityModelLayers.CAMEL_HUSK_BABY, texturedModelData33.transform(CamelEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.CAVE_SPIDER, texturedModelData30.transform(ModelTransformer.scaling(0.7F)));
		builder.put(EntityModelLayers.CHEST, ChestBlockModel.getSingleTexturedModelData());
		builder.put(EntityModelLayers.CHEST_MINECART, texturedModelData2);
		builder.put(EntityModelLayers.CHICKEN, texturedModelData34);
		builder.put(EntityModelLayers.CHICKEN_BABY, texturedModelData34.transform(ChickenEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.COD, CodEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.COLD_CHICKEN, texturedModelData12);
		builder.put(EntityModelLayers.COLD_CHICKEN_BABY, texturedModelData12.transform(ChickenEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.COLD_COW, texturedModelData13);
		builder.put(EntityModelLayers.COLD_COW_BABY, texturedModelData13.transform(CowEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.COLD_PIG, texturedModelData14);
		builder.put(EntityModelLayers.COLD_PIG_BABY, texturedModelData14.transform(PigEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.COMMAND_BLOCK_MINECART, texturedModelData2);
		builder.put(EntityModelLayers.CONDUIT_EYE, ConduitBlockEntityRenderer.getEyeTexturedModelData());
		builder.put(EntityModelLayers.CONDUIT_WIND, ConduitBlockEntityRenderer.getWindTexturedModelData());
		builder.put(EntityModelLayers.CONDUIT_SHELL, ConduitBlockEntityRenderer.getShellTexturedModelData());
		builder.put(EntityModelLayers.CONDUIT, ConduitBlockEntityRenderer.getPlainTexturedModelData());
		builder.put(EntityModelLayers.COPPER_GOLEM, CopperGolemEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.COPPER_GOLEM_EYES, CopperGolemEntityModel.getEyesTexturedModelData());
		builder.put(EntityModelLayers.COPPER_GOLEM_RUNNING, CopperGolemEntityModel.getRunningTexturedModelData());
		builder.put(EntityModelLayers.COPPER_GOLEM_SITTING, CopperGolemEntityModel.getSittingTexturedModelData());
		builder.put(EntityModelLayers.COPPER_GOLEM_STAR, CopperGolemEntityModel.getStarTexturedModelData());
		builder.put(EntityModelLayers.COW, texturedModelData11);
		builder.put(EntityModelLayers.COW_BABY, texturedModelData11.transform(CowEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.CREAKING, CreakingEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.CREAKING_EYES, CreakingEntityModel.getEyesTexturedModelData());
		builder.put(EntityModelLayers.CREEPER, CreeperEntityModel.getTexturedModelData(Dilation.NONE));
		builder.put(EntityModelLayers.CREEPER_ARMOR, CreeperEntityModel.getTexturedModelData(new Dilation(2.0F)));
		builder.put(EntityModelLayers.CREEPER_HEAD, texturedModelData3);
		builder.put(EntityModelLayers.DECORATED_POT_BASE, DecoratedPotBlockEntityRenderer.getTopBottomNeckTexturedModelData());
		builder.put(EntityModelLayers.DECORATED_POT_SIDES, DecoratedPotBlockEntityRenderer.getSidesTexturedModelData());
		builder.put(EntityModelLayers.DOLPHIN, texturedModelData52);
		builder.put(EntityModelLayers.DOLPHIN_BABY, texturedModelData52.transform(DolphinEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.DONKEY, DonkeyEntityModel.getTexturedModelData(0.87F));
		builder.put(EntityModelLayers.DONKEY_BABY, DonkeyEntityModel.getBabyTexturedModelData(0.87F));
		builder.put(EntityModelLayers.DONKEY_SADDLE, DonkeyEntityModel.getSaddleTexturedModelData(0.87F, false));
		builder.put(EntityModelLayers.DONKEY_BABY_SADDLE, DonkeyEntityModel.getSaddleTexturedModelData(0.87F, true));
		builder.put(EntityModelLayers.DOUBLE_CHEST_LEFT, ChestBlockModel.getDoubleChestLeftTexturedBlockData());
		builder.put(EntityModelLayers.DOUBLE_CHEST_RIGHT, ChestBlockModel.getDoubleChestRightTexturedBlockData());
		builder.put(EntityModelLayers.DRAGON_SKULL, DragonHeadEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.DROWNED, texturedModelData49);
		EntityModelLayers.DROWNED_EQUIPMENT.addTo(equipmentModelData, builder);
		builder.put(EntityModelLayers.DROWNED_OUTER, texturedModelData50);
		builder.put(EntityModelLayers.DROWNED_BABY, texturedModelData49.transform(BipedEntityModel.BABY_TRANSFORMER));
		EntityModelLayers.DROWNED_BABY_EQUIPMENT.addTo(equipmentModelData2, builder);
		builder.put(EntityModelLayers.DROWNED_BABY_OUTER, texturedModelData50.transform(BipedEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.ELDER_GUARDIAN, GuardianEntityModel.getElderTexturedModelData());
		builder.put(EntityModelLayers.ELYTRA, texturedModelData15);
		builder.put(EntityModelLayers.ELYTRA_BABY, texturedModelData15.transform(ElytraEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.ENDERMAN, EndermanEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.ENDERMITE, EndermiteEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.ENDER_DRAGON, DragonEntityModel.createTexturedModelData());
		builder.put(EntityModelLayers.END_CRYSTAL, EndCrystalEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.EVOKER, texturedModelData8);
		builder.put(EntityModelLayers.EVOKER_FANGS, EvokerFangsEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.FOX, FoxEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.FOX_BABY, FoxEntityModel.getTexturedModelData().transform(FoxEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.FROG, FrogEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.FURNACE_MINECART, texturedModelData2);
		builder.put(EntityModelLayers.GHAST, GhastEntityModel.getTexturedModelData());
		ModelTransformer modelTransformer2 = ModelTransformer.scaling(6.0F);
		builder.put(EntityModelLayers.GIANT, texturedModelData.transform(modelTransformer2));
		EntityModelLayers.GIANT_EQUIPMENT.addTo(equipmentModelData.map(modelData -> modelData.transform(modelTransformer2)), builder);
		builder.put(EntityModelLayers.GLOW_SQUID, texturedModelData51);
		builder.put(EntityModelLayers.GLOW_SQUID_BABY, texturedModelData51.transform(SquidEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.GOAT, texturedModelData35);
		builder.put(EntityModelLayers.GOAT_BABY, texturedModelData35.transform(GoatEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.GUARDIAN, GuardianEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.HAPPY_GHAST, HappyGhastEntityModel.getTexturedModelData(false, Dilation.NONE));
		builder.put(
			EntityModelLayers.HAPPY_GHAST_BABY, HappyGhastEntityModel.getTexturedModelData(true, Dilation.NONE).transform(HappyGhastEntityModel.BABY_TRANSFORMER)
		);
		builder.put(EntityModelLayers.HAPPY_GHAST_HARNESS, HappyGhastHarnessEntityModel.getTexturedModelData(false));
		builder.put(
			EntityModelLayers.HAPPY_GHAST_BABY_HARNESS, HappyGhastHarnessEntityModel.getTexturedModelData(true).transform(HappyGhastEntityModel.BABY_TRANSFORMER)
		);
		builder.put(EntityModelLayers.HAPPY_GHAST_ROPES, HappyGhastEntityModel.getTexturedModelData(false, new Dilation(0.2F)));
		builder.put(
			EntityModelLayers.HAPPY_GHAST_BABY_ROPES,
			HappyGhastEntityModel.getTexturedModelData(true, new Dilation(0.2F)).transform(HappyGhastEntityModel.BABY_TRANSFORMER)
		);
		builder.put(EntityModelLayers.HOGLIN, texturedModelData25);
		builder.put(EntityModelLayers.HOGLIN_BABY, texturedModelData26);
		builder.put(EntityModelLayers.HOPPER_MINECART, texturedModelData2);
		ModelTransformer modelTransformer3 = ModelTransformer.scaling(1.1F);
		builder.put(EntityModelLayers.HORSE, texturedModelData4.transform(modelTransformer3));
		builder.put(EntityModelLayers.HORSE_BABY, texturedModelData5.transform(modelTransformer3));
		builder.put(
			EntityModelLayers.HORSE_ARMOR, TexturedModelData.of(AbstractHorseEntityModel.getModelData(new Dilation(0.1F)), 64, 64).transform(modelTransformer3)
		);
		builder.put(
			EntityModelLayers.HORSE_ARMOR_BABY,
			TexturedModelData.of(AbstractHorseEntityModel.getBabyHorseModelData(new Dilation(0.1F)), 64, 64).transform(modelTransformer3)
		);
		builder.put(EntityModelLayers.HORSE_SADDLE, texturedModelData6.transform(modelTransformer3));
		builder.put(EntityModelLayers.HORSE_BABY_SADDLE, texturedModelData7.transform(modelTransformer3));
		ModelTransformer modelTransformer4 = ModelTransformer.scaling(1.0625F);
		builder.put(EntityModelLayers.HUSK, texturedModelData.transform(modelTransformer4));
		EntityModelLayers.HUSK_EQUIPMENT.addTo(equipmentModelData.map(modelData -> modelData.transform(modelTransformer4)), builder);
		builder.put(EntityModelLayers.HUSK_BABY, texturedModelData.transform(BipedEntityModel.BABY_TRANSFORMER).transform(modelTransformer4));
		EntityModelLayers.HUSK_BABY_EQUIPMENT.addTo(equipmentModelData2.map(modelData -> modelData.transform(modelTransformer4)), builder);
		builder.put(EntityModelLayers.ILLUSIONER, texturedModelData8);
		builder.put(EntityModelLayers.IRON_GOLEM, IronGolemEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.LEASH_KNOT, LeashKnotEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.LLAMA, texturedModelData22);
		builder.put(EntityModelLayers.LLAMA_BABY, texturedModelData22.transform(LlamaEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.LLAMA_DECOR, texturedModelData23);
		builder.put(EntityModelLayers.LLAMA_BABY_DECOR, texturedModelData23.transform(LlamaEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.LLAMA_SPIT, LlamaSpitEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.MAGMA_CUBE, MagmaCubeEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.MINECART, texturedModelData2);
		builder.put(EntityModelLayers.MOOSHROOM, texturedModelData11);
		builder.put(EntityModelLayers.MOOSHROOM_BABY, texturedModelData11.transform(CowEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.MULE, DonkeyEntityModel.getTexturedModelData(0.92F));
		builder.put(EntityModelLayers.MULE_BABY, DonkeyEntityModel.getBabyTexturedModelData(0.92F));
		builder.put(EntityModelLayers.MULE_SADDLE, DonkeyEntityModel.getSaddleTexturedModelData(0.92F, false));
		builder.put(EntityModelLayers.MULE_BABY_SADDLE, DonkeyEntityModel.getSaddleTexturedModelData(0.92F, true));
		builder.put(EntityModelLayers.NAUTILUS, NautilusEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.NAUTILUS_BABY, NautilusEntityModel.getBabyTexturedModelData());
		builder.put(EntityModelLayers.NAUTILUS_SADDLE, texturedModelData54);
		builder.put(EntityModelLayers.NAUTILUS_ARMOR, NautilusArmorEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.ZOMBIE_NAUTILUS, NautilusEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.ZOMBIE_NAUTILUS_CORAL, ZombieNautilusCoralEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.OCELOT, texturedModelData16);
		builder.put(EntityModelLayers.OCELOT_BABY, texturedModelData17);
		builder.put(EntityModelLayers.PANDA, texturedModelData36);
		builder.put(EntityModelLayers.PANDA_BABY, texturedModelData36.transform(PandaEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.PARCHED, SkeletonEntityModel.getParchedTexturedModelData());
		EntityModelLayers.PARCHED_EQUIPMENT.addTo(equipmentModelData, builder);
		builder.put(EntityModelLayers.PARCHED_OUTER, TexturedModelData.of(BipedEntityModel.getModelData(new Dilation(0.25F), 0.0F), 64, 32));
		builder.put(EntityModelLayers.PARROT, ParrotEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.PHANTOM, PhantomEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.PIG, texturedModelData37);
		builder.put(EntityModelLayers.PIG_BABY, texturedModelData37.transform(PigEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.PIG_SADDLE, texturedModelData38);
		builder.put(EntityModelLayers.PIG_BABY_SADDLE, texturedModelData38.transform(PigEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.PIGLIN, texturedModelData19);
		EntityModelLayers.PIGLIN_EQUIPMENT.addTo(equipmentModelData4, builder);
		builder.put(EntityModelLayers.PIGLIN_BRUTE, texturedModelData19);
		EntityModelLayers.PIGLIN_BRUTE_EQUIPMENT.addTo(equipmentModelData4, builder);
		builder.put(EntityModelLayers.PIGLIN_BABY, texturedModelData19.transform(BipedEntityModel.BABY_TRANSFORMER));
		EntityModelLayers.PIGLIN_BABY_EQUIPMENT.addTo(equipmentModelData5, builder);
		builder.put(EntityModelLayers.PIGLIN_HEAD, texturedModelData20);
		builder.put(EntityModelLayers.PILLAGER, texturedModelData8);
		builder.put(EntityModelLayers.PLAYER, TexturedModelData.of(PlayerEntityModel.getTexturedModelData(Dilation.NONE, false), 64, 64));
		builder.put(EntityModelLayers.PLAYER_EARS, Deadmau5EarsEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.PLAYER_CAPE, PlayerCapeModel.getTexturedModelData());
		builder.put(EntityModelLayers.PLAYER_HEAD, texturedModelData21);
		EntityModelLayers.PLAYER_EQUIPMENT.addTo(equipmentModelData3, builder);
		builder.put(EntityModelLayers.PLAYER_SLIM, TexturedModelData.of(PlayerEntityModel.getTexturedModelData(Dilation.NONE, true), 64, 64));
		EntityModelLayers.PLAYER_SLIM.addTo(equipmentModelData3, builder);
		builder.put(EntityModelLayers.SPIN_ATTACK, TridentRiptideEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.POLAR_BEAR, PolarBearEntityModel.getTexturedModelData(false));
		builder.put(EntityModelLayers.POLAR_BEAR_BABY, PolarBearEntityModel.getTexturedModelData(true));
		builder.put(EntityModelLayers.PUFFERFISH_BIG, LargePufferfishEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.PUFFERFISH_MEDIUM, MediumPufferfishEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.PUFFERFISH_SMALL, SmallPufferfishEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.RABBIT, RabbitEntityModel.getTexturedModelData(false));
		builder.put(EntityModelLayers.RABBIT_BABY, RabbitEntityModel.getTexturedModelData(true));
		builder.put(EntityModelLayers.RAVAGER, RavagerEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.SALMON, texturedModelData53);
		builder.put(EntityModelLayers.SALMON_SMALL, texturedModelData53.transform(SalmonEntityModel.SMALL_TRANSFORMER));
		builder.put(EntityModelLayers.SALMON_LARGE, texturedModelData53.transform(SalmonEntityModel.LARGE_TRANSFORMER));
		builder.put(EntityModelLayers.SHEEP, texturedModelData39);
		builder.put(EntityModelLayers.SHEEP_BABY, texturedModelData39.transform(SheepEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.SHEEP_WOOL, texturedModelData40);
		builder.put(EntityModelLayers.SHEEP_BABY_WOOL, texturedModelData40.transform(SheepEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.SHEEP_WOOL_UNDERCOAT, texturedModelData39);
		builder.put(EntityModelLayers.SHEEP_BABY_WOOL_UNDERCOAT, texturedModelData39.transform(SheepEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.SHIELD, ShieldEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.SHULKER, ShulkerEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.SHULKER_BOX, ShulkerEntityModel.getShulkerBoxTexturedModelData());
		builder.put(EntityModelLayers.SHULKER_BULLET, ShulkerBulletEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.SILVERFISH, SilverfishEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.SKELETON, texturedModelData27);
		EntityModelLayers.SKELETON_EQUIPMENT.addTo(equipmentModelData, builder);
		builder.put(EntityModelLayers.SKELETON_HORSE, texturedModelData4);
		builder.put(EntityModelLayers.SKELETON_HORSE_BABY, texturedModelData5);
		builder.put(EntityModelLayers.SKELETON_HORSE_SADDLE, texturedModelData6);
		builder.put(EntityModelLayers.SKELETON_HORSE_BABY_SADDLE, texturedModelData7);
		builder.put(EntityModelLayers.SKELETON_SKULL, texturedModelData3);
		builder.put(EntityModelLayers.SLIME, SlimeEntityModel.getInnerTexturedModelData());
		builder.put(EntityModelLayers.SLIME_OUTER, SlimeEntityModel.getOuterTexturedModelData());
		builder.put(EntityModelLayers.SNIFFER, texturedModelData41);
		builder.put(EntityModelLayers.SNIFFER_BABY, texturedModelData41.transform(SnifferEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.SNOW_GOLEM, SnowGolemEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.SPAWNER_MINECART, texturedModelData2);
		builder.put(EntityModelLayers.SPIDER, texturedModelData30);
		builder.put(EntityModelLayers.SQUID, texturedModelData51);
		builder.put(EntityModelLayers.SQUID_BABY, texturedModelData51.transform(SquidEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.STRAY, texturedModelData27);
		EntityModelLayers.STRAY_EQUIPMENT.addTo(equipmentModelData, builder);
		builder.put(EntityModelLayers.STRAY_OUTER, TexturedModelData.of(BipedEntityModel.getModelData(new Dilation(0.25F), 0.0F), 64, 32));
		builder.put(EntityModelLayers.STRIDER, texturedModelData24);
		builder.put(EntityModelLayers.STRIDER_SADDLE, texturedModelData24);
		builder.put(EntityModelLayers.STRIDER_BABY, texturedModelData24.transform(StriderEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.STRIDER_BABY_SADDLE, texturedModelData24.transform(StriderEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.TADPOLE, TadpoleEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.TNT_MINECART, texturedModelData2);
		builder.put(EntityModelLayers.TRADER_LLAMA, texturedModelData22);
		builder.put(EntityModelLayers.TRADER_LLAMA_BABY, texturedModelData22.transform(LlamaEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.TRIDENT, TridentEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.TROPICAL_FISH_LARGE, LargeTropicalFishEntityModel.getTexturedModelData(Dilation.NONE));
		builder.put(EntityModelLayers.TROPICAL_FISH_LARGE_PATTERN, LargeTropicalFishEntityModel.getTexturedModelData(FISH_PATTERN_DILATION));
		builder.put(EntityModelLayers.TROPICAL_FISH_SMALL, SmallTropicalFishEntityModel.getTexturedModelData(Dilation.NONE));
		builder.put(EntityModelLayers.TROPICAL_FISH_SMALL_PATTERN, SmallTropicalFishEntityModel.getTexturedModelData(FISH_PATTERN_DILATION));
		builder.put(EntityModelLayers.TURTLE, texturedModelData42);
		builder.put(EntityModelLayers.TURTLE_BABY, texturedModelData42.transform(TurtleEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.UNDEAD_HORSE_ARMOR, TexturedModelData.of(AbstractHorseEntityModel.getModelData(new Dilation(0.1F)), 64, 64));
		builder.put(EntityModelLayers.UNDEAD_HORSE_BABY_ARMOR, TexturedModelData.of(AbstractHorseEntityModel.getBabyHorseModelData(new Dilation(0.1F)), 64, 64));
		builder.put(EntityModelLayers.VEX, VexEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.VILLAGER, texturedModelData28);
		builder.put(EntityModelLayers.VILLAGER_NO_HAT, texturedModelData29);
		builder.put(EntityModelLayers.VILLAGER_BABY, texturedModelData28.transform(VillagerResemblingModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.VILLAGER_BABY_NO_HAT, texturedModelData29.transform(VillagerResemblingModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.VINDICATOR, texturedModelData8);
		builder.put(EntityModelLayers.WARDEN, WardenEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.WARDEN_TENDRILS, WardenEntityModel.getTendrilsTexturedModelData());
		builder.put(EntityModelLayers.WARDEN_HEART, WardenEntityModel.getHeartTexturedModelData());
		builder.put(EntityModelLayers.WARDEN_BIOLUMINESCENT, WardenEntityModel.getBioluminescentTexturedModelData());
		builder.put(EntityModelLayers.WARDEN_PULSATING_SPOTS, WardenEntityModel.getPulsatingSpotsTexturedModelData());
		builder.put(EntityModelLayers.WARM_COW, texturedModelData43);
		builder.put(EntityModelLayers.WARM_COW_BABY, texturedModelData43.transform(CowEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.WANDERING_TRADER, texturedModelData28);
		builder.put(EntityModelLayers.WIND_CHARGE, WindChargeEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.WITCH, WitchEntityModel.getTexturedModelData().transform(modelTransformer));
		builder.put(EntityModelLayers.WITHER, WitherEntityModel.getTexturedModelData(Dilation.NONE));
		builder.put(EntityModelLayers.WITHER_ARMOR, WitherEntityModel.getTexturedModelData(HAT_DILATION));
		builder.put(EntityModelLayers.WITHER_SKULL, WitherSkullEntityRenderer.getTexturedModelData());
		ModelTransformer modelTransformer5 = ModelTransformer.scaling(1.2F);
		builder.put(EntityModelLayers.WITHER_SKELETON, texturedModelData27.transform(modelTransformer5));
		EntityModelLayers.WITHER_SKELETON_EQUIPMENT.addTo(equipmentModelData.map(modelData -> modelData.transform(modelTransformer5)), builder);
		builder.put(EntityModelLayers.WITHER_SKELETON_SKULL, texturedModelData3);
		builder.put(EntityModelLayers.WOLF, texturedModelData44);
		builder.put(EntityModelLayers.WOLF_ARMOR, texturedModelData45);
		builder.put(EntityModelLayers.WOLF_BABY, texturedModelData44.transform(WolfEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.WOLF_BABY_ARMOR, texturedModelData45.transform(WolfEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.ZOGLIN, texturedModelData25);
		builder.put(EntityModelLayers.ZOGLIN_BABY, texturedModelData26);
		builder.put(EntityModelLayers.ZOMBIE, texturedModelData);
		EntityModelLayers.ZOMBIE_EQUIPMENT.addTo(equipmentModelData, builder);
		builder.put(EntityModelLayers.ZOMBIE_BABY, texturedModelData.transform(BipedEntityModel.BABY_TRANSFORMER));
		EntityModelLayers.ZOMBIE_BABY_EQUIPMENT.addTo(equipmentModelData2, builder);
		builder.put(EntityModelLayers.ZOMBIE_HEAD, texturedModelData21);
		builder.put(EntityModelLayers.ZOMBIE_HORSE, texturedModelData4);
		builder.put(EntityModelLayers.ZOMBIE_HORSE_BABY, texturedModelData5);
		builder.put(EntityModelLayers.ZOMBIE_HORSE_SADDLE, texturedModelData6);
		builder.put(EntityModelLayers.ZOMBIE_HORSE_BABY_SADDLE, texturedModelData7);
		builder.put(EntityModelLayers.ZOMBIE_VILLAGER, texturedModelData46);
		builder.put(EntityModelLayers.ZOMBIE_VILLAGER_NO_HAT, texturedModelData47);
		EquipmentModelData<TexturedModelData> equipmentModelData7 = ZombieVillagerEntityModel.getEquipmentModelData(HAT_DILATION, ARMOR_DILATION);
		EntityModelLayers.ZOMBIE_VILLAGER_EQUIPMENT.addTo(equipmentModelData7, builder);
		builder.put(EntityModelLayers.ZOMBIE_VILLAGER_BABY, texturedModelData46.transform(BipedEntityModel.BABY_TRANSFORMER));
		builder.put(EntityModelLayers.ZOMBIE_VILLAGER_BABY_NO_HAT, texturedModelData47.transform(BipedEntityModel.BABY_TRANSFORMER));
		EntityModelLayers.ZOMBIE_VILLAGER_BABY_EQUIPMENT.addTo(equipmentModelData7.map(modelData -> modelData.transform(BipedEntityModel.BABY_TRANSFORMER)), builder);
		builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN, texturedModelData19);
		EntityModelLayers.ZOMBIFIED_PIGLIN_EQUIPMENT.addTo(equipmentModelData4, builder);
		builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN_BABY, texturedModelData19.transform(BipedEntityModel.BABY_TRANSFORMER));
		EntityModelLayers.ZOMBIFIED_PIGLIN_BABY_EQUIPMENT.addTo(equipmentModelData5, builder);
		builder.put(EntityModelLayers.BAMBOO_BOAT, RaftEntityModel.getTexturedModelData());
		builder.put(EntityModelLayers.BAMBOO_CHEST_BOAT, RaftEntityModel.getChestTexturedModelData());
		TexturedModelData texturedModelData55 = BoatEntityModel.getTexturedModelData();
		TexturedModelData texturedModelData56 = BoatEntityModel.getChestTexturedModelData();
		builder.put(EntityModelLayers.OAK_BOAT, texturedModelData55);
		builder.put(EntityModelLayers.OAK_CHEST_BOAT, texturedModelData56);
		builder.put(EntityModelLayers.SPRUCE_BOAT, texturedModelData55);
		builder.put(EntityModelLayers.SPRUCE_CHEST_BOAT, texturedModelData56);
		builder.put(EntityModelLayers.BIRCH_BOAT, texturedModelData55);
		builder.put(EntityModelLayers.BIRCH_CHEST_BOAT, texturedModelData56);
		builder.put(EntityModelLayers.JUNGLE_BOAT, texturedModelData55);
		builder.put(EntityModelLayers.JUNGLE_CHEST_BOAT, texturedModelData56);
		builder.put(EntityModelLayers.ACACIA_BOAT, texturedModelData55);
		builder.put(EntityModelLayers.ACACIA_CHEST_BOAT, texturedModelData56);
		builder.put(EntityModelLayers.CHERRY_BOAT, texturedModelData55);
		builder.put(EntityModelLayers.CHERRY_CHEST_BOAT, texturedModelData56);
		builder.put(EntityModelLayers.DARK_OAK_BOAT, texturedModelData55);
		builder.put(EntityModelLayers.DARK_OAK_CHEST_BOAT, texturedModelData56);
		builder.put(EntityModelLayers.PALE_OAK_BOAT, texturedModelData55);
		builder.put(EntityModelLayers.PALE_OAK_CHEST_BOAT, texturedModelData56);
		builder.put(EntityModelLayers.MANGROVE_BOAT, texturedModelData55);
		builder.put(EntityModelLayers.MANGROVE_CHEST_BOAT, texturedModelData56);
		TexturedModelData texturedModelData57 = SignBlockEntityRenderer.getTexturedModelData(true);
		TexturedModelData texturedModelData58 = SignBlockEntityRenderer.getTexturedModelData(false);
		WoodType.stream().forEach(woodType -> {
			builder.put(EntityModelLayers.createStandingSign(woodType), texturedModelData57);
			builder.put(EntityModelLayers.createWallSign(woodType), texturedModelData58);

			for (HangingSignBlockEntityRenderer.AttachmentType attachmentType : HangingSignBlockEntityRenderer.AttachmentType.values()) {
				TexturedModelData texturedModelData3x = HangingSignBlockEntityRenderer.getTexturedModelData(attachmentType);
				builder.put(EntityModelLayers.createHangingSign(woodType, attachmentType), texturedModelData3x);
			}
		});
		ImmutableMap<EntityModelLayer, TexturedModelData> immutableMap = builder.build();
		List<EntityModelLayer> list = EntityModelLayers.getLayers().filter(layer -> !immutableMap.containsKey(layer)).toList();
		if (!list.isEmpty()) {
			throw new IllegalStateException("Missing layer definitions: " + list);
		} else {
			return immutableMap;
		}
	}
}
