package net.minecraft.client.render;

import com.google.common.collect.Maps;
import java.util.Map;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.block.LeavesBlock;
import net.minecraft.fluid.Fluid;
import net.minecraft.fluid.FluidState;
import net.minecraft.fluid.Fluids;
import net.minecraft.util.Util;

@Environment(EnvType.CLIENT)
public class BlockRenderLayers {
	private static final Map<Block, BlockRenderLayer> BLOCKS = Util.make(Maps.<Block, BlockRenderLayer>newHashMap(), map -> {
		BlockRenderLayer blockRenderLayer = BlockRenderLayer.TRIPWIRE;
		map.put(Blocks.TRIPWIRE, blockRenderLayer);
		BlockRenderLayer blockRenderLayer2 = BlockRenderLayer.CUTOUT;
		map.put(Blocks.GRASS_BLOCK, blockRenderLayer2);
		map.put(Blocks.IRON_BARS, blockRenderLayer2);
		Blocks.COPPER_BARS.forEach(block -> map.put(block, blockRenderLayer2));
		map.put(Blocks.TRIPWIRE_HOOK, blockRenderLayer2);
		map.put(Blocks.HOPPER, blockRenderLayer2);
		map.put(Blocks.IRON_CHAIN, blockRenderLayer2);
		Blocks.COPPER_CHAINS.forEach(block -> map.put(block, blockRenderLayer2));
		map.put(Blocks.JUNGLE_LEAVES, blockRenderLayer2);
		map.put(Blocks.OAK_LEAVES, blockRenderLayer2);
		map.put(Blocks.SPRUCE_LEAVES, blockRenderLayer2);
		map.put(Blocks.ACACIA_LEAVES, blockRenderLayer2);
		map.put(Blocks.CHERRY_LEAVES, blockRenderLayer2);
		map.put(Blocks.BIRCH_LEAVES, blockRenderLayer2);
		map.put(Blocks.DARK_OAK_LEAVES, blockRenderLayer2);
		map.put(Blocks.PALE_OAK_LEAVES, blockRenderLayer2);
		map.put(Blocks.AZALEA_LEAVES, blockRenderLayer2);
		map.put(Blocks.FLOWERING_AZALEA_LEAVES, blockRenderLayer2);
		map.put(Blocks.MANGROVE_ROOTS, blockRenderLayer2);
		map.put(Blocks.MANGROVE_LEAVES, blockRenderLayer2);
		map.put(Blocks.OAK_SAPLING, blockRenderLayer2);
		map.put(Blocks.SPRUCE_SAPLING, blockRenderLayer2);
		map.put(Blocks.BIRCH_SAPLING, blockRenderLayer2);
		map.put(Blocks.JUNGLE_SAPLING, blockRenderLayer2);
		map.put(Blocks.ACACIA_SAPLING, blockRenderLayer2);
		map.put(Blocks.CHERRY_SAPLING, blockRenderLayer2);
		map.put(Blocks.DARK_OAK_SAPLING, blockRenderLayer2);
		map.put(Blocks.PALE_OAK_SAPLING, blockRenderLayer2);
		map.put(Blocks.WHITE_BED, blockRenderLayer2);
		map.put(Blocks.ORANGE_BED, blockRenderLayer2);
		map.put(Blocks.MAGENTA_BED, blockRenderLayer2);
		map.put(Blocks.LIGHT_BLUE_BED, blockRenderLayer2);
		map.put(Blocks.YELLOW_BED, blockRenderLayer2);
		map.put(Blocks.LIME_BED, blockRenderLayer2);
		map.put(Blocks.PINK_BED, blockRenderLayer2);
		map.put(Blocks.GRAY_BED, blockRenderLayer2);
		map.put(Blocks.LIGHT_GRAY_BED, blockRenderLayer2);
		map.put(Blocks.CYAN_BED, blockRenderLayer2);
		map.put(Blocks.PURPLE_BED, blockRenderLayer2);
		map.put(Blocks.BLUE_BED, blockRenderLayer2);
		map.put(Blocks.BROWN_BED, blockRenderLayer2);
		map.put(Blocks.GREEN_BED, blockRenderLayer2);
		map.put(Blocks.RED_BED, blockRenderLayer2);
		map.put(Blocks.BLACK_BED, blockRenderLayer2);
		map.put(Blocks.POWERED_RAIL, blockRenderLayer2);
		map.put(Blocks.DETECTOR_RAIL, blockRenderLayer2);
		map.put(Blocks.COBWEB, blockRenderLayer2);
		map.put(Blocks.SHORT_GRASS, blockRenderLayer2);
		map.put(Blocks.FERN, blockRenderLayer2);
		map.put(Blocks.BUSH, blockRenderLayer2);
		map.put(Blocks.DEAD_BUSH, blockRenderLayer2);
		map.put(Blocks.SHORT_DRY_GRASS, blockRenderLayer2);
		map.put(Blocks.TALL_DRY_GRASS, blockRenderLayer2);
		map.put(Blocks.SEAGRASS, blockRenderLayer2);
		map.put(Blocks.TALL_SEAGRASS, blockRenderLayer2);
		map.put(Blocks.DANDELION, blockRenderLayer2);
		map.put(Blocks.OPEN_EYEBLOSSOM, blockRenderLayer2);
		map.put(Blocks.CLOSED_EYEBLOSSOM, blockRenderLayer2);
		map.put(Blocks.POPPY, blockRenderLayer2);
		map.put(Blocks.BLUE_ORCHID, blockRenderLayer2);
		map.put(Blocks.ALLIUM, blockRenderLayer2);
		map.put(Blocks.AZURE_BLUET, blockRenderLayer2);
		map.put(Blocks.RED_TULIP, blockRenderLayer2);
		map.put(Blocks.ORANGE_TULIP, blockRenderLayer2);
		map.put(Blocks.WHITE_TULIP, blockRenderLayer2);
		map.put(Blocks.PINK_TULIP, blockRenderLayer2);
		map.put(Blocks.OXEYE_DAISY, blockRenderLayer2);
		map.put(Blocks.CORNFLOWER, blockRenderLayer2);
		map.put(Blocks.WITHER_ROSE, blockRenderLayer2);
		map.put(Blocks.LILY_OF_THE_VALLEY, blockRenderLayer2);
		map.put(Blocks.BROWN_MUSHROOM, blockRenderLayer2);
		map.put(Blocks.RED_MUSHROOM, blockRenderLayer2);
		map.put(Blocks.TORCH, blockRenderLayer2);
		map.put(Blocks.WALL_TORCH, blockRenderLayer2);
		map.put(Blocks.SOUL_TORCH, blockRenderLayer2);
		map.put(Blocks.SOUL_WALL_TORCH, blockRenderLayer2);
		map.put(Blocks.COPPER_TORCH, blockRenderLayer2);
		map.put(Blocks.COPPER_WALL_TORCH, blockRenderLayer2);
		map.put(Blocks.FIRE, blockRenderLayer2);
		map.put(Blocks.SOUL_FIRE, blockRenderLayer2);
		map.put(Blocks.SPAWNER, blockRenderLayer2);
		map.put(Blocks.TRIAL_SPAWNER, blockRenderLayer2);
		map.put(Blocks.VAULT, blockRenderLayer2);
		map.put(Blocks.WHEAT, blockRenderLayer2);
		map.put(Blocks.OAK_DOOR, blockRenderLayer2);
		map.put(Blocks.LADDER, blockRenderLayer2);
		map.put(Blocks.RAIL, blockRenderLayer2);
		map.put(Blocks.IRON_DOOR, blockRenderLayer2);
		map.put(Blocks.REDSTONE_TORCH, blockRenderLayer2);
		map.put(Blocks.REDSTONE_WALL_TORCH, blockRenderLayer2);
		map.put(Blocks.CACTUS, blockRenderLayer2);
		map.put(Blocks.SUGAR_CANE, blockRenderLayer2);
		map.put(Blocks.REPEATER, blockRenderLayer2);
		map.put(Blocks.OAK_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.SPRUCE_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.BIRCH_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.JUNGLE_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.ACACIA_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.CHERRY_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.DARK_OAK_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.PALE_OAK_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.CRIMSON_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.WARPED_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.MANGROVE_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.BAMBOO_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.COPPER_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.EXPOSED_COPPER_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.WEATHERED_COPPER_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.OXIDIZED_COPPER_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.WAXED_COPPER_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.WAXED_EXPOSED_COPPER_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.WAXED_WEATHERED_COPPER_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.WAXED_OXIDIZED_COPPER_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.ATTACHED_PUMPKIN_STEM, blockRenderLayer2);
		map.put(Blocks.ATTACHED_MELON_STEM, blockRenderLayer2);
		map.put(Blocks.PUMPKIN_STEM, blockRenderLayer2);
		map.put(Blocks.MELON_STEM, blockRenderLayer2);
		map.put(Blocks.VINE, blockRenderLayer2);
		map.put(Blocks.PALE_MOSS_CARPET, blockRenderLayer2);
		map.put(Blocks.PALE_HANGING_MOSS, blockRenderLayer2);
		map.put(Blocks.GLOW_LICHEN, blockRenderLayer2);
		map.put(Blocks.RESIN_CLUMP, blockRenderLayer2);
		map.put(Blocks.LILY_PAD, blockRenderLayer2);
		map.put(Blocks.NETHER_WART, blockRenderLayer2);
		map.put(Blocks.BREWING_STAND, blockRenderLayer2);
		map.put(Blocks.COCOA, blockRenderLayer2);
		map.put(Blocks.FLOWER_POT, blockRenderLayer2);
		map.put(Blocks.POTTED_OAK_SAPLING, blockRenderLayer2);
		map.put(Blocks.POTTED_SPRUCE_SAPLING, blockRenderLayer2);
		map.put(Blocks.POTTED_BIRCH_SAPLING, blockRenderLayer2);
		map.put(Blocks.POTTED_JUNGLE_SAPLING, blockRenderLayer2);
		map.put(Blocks.POTTED_ACACIA_SAPLING, blockRenderLayer2);
		map.put(Blocks.POTTED_CHERRY_SAPLING, blockRenderLayer2);
		map.put(Blocks.POTTED_DARK_OAK_SAPLING, blockRenderLayer2);
		map.put(Blocks.POTTED_PALE_OAK_SAPLING, blockRenderLayer2);
		map.put(Blocks.POTTED_MANGROVE_PROPAGULE, blockRenderLayer2);
		map.put(Blocks.POTTED_FERN, blockRenderLayer2);
		map.put(Blocks.POTTED_DANDELION, blockRenderLayer2);
		map.put(Blocks.POTTED_POPPY, blockRenderLayer2);
		map.put(Blocks.POTTED_OPEN_EYEBLOSSOM, blockRenderLayer2);
		map.put(Blocks.POTTED_CLOSED_EYEBLOSSOM, blockRenderLayer2);
		map.put(Blocks.POTTED_BLUE_ORCHID, blockRenderLayer2);
		map.put(Blocks.POTTED_ALLIUM, blockRenderLayer2);
		map.put(Blocks.POTTED_AZURE_BLUET, blockRenderLayer2);
		map.put(Blocks.POTTED_RED_TULIP, blockRenderLayer2);
		map.put(Blocks.POTTED_ORANGE_TULIP, blockRenderLayer2);
		map.put(Blocks.POTTED_WHITE_TULIP, blockRenderLayer2);
		map.put(Blocks.POTTED_PINK_TULIP, blockRenderLayer2);
		map.put(Blocks.POTTED_OXEYE_DAISY, blockRenderLayer2);
		map.put(Blocks.POTTED_CORNFLOWER, blockRenderLayer2);
		map.put(Blocks.POTTED_LILY_OF_THE_VALLEY, blockRenderLayer2);
		map.put(Blocks.POTTED_WITHER_ROSE, blockRenderLayer2);
		map.put(Blocks.POTTED_RED_MUSHROOM, blockRenderLayer2);
		map.put(Blocks.POTTED_BROWN_MUSHROOM, blockRenderLayer2);
		map.put(Blocks.POTTED_DEAD_BUSH, blockRenderLayer2);
		map.put(Blocks.POTTED_CACTUS, blockRenderLayer2);
		map.put(Blocks.POTTED_AZALEA_BUSH, blockRenderLayer2);
		map.put(Blocks.POTTED_FLOWERING_AZALEA_BUSH, blockRenderLayer2);
		map.put(Blocks.POTTED_TORCHFLOWER, blockRenderLayer2);
		map.put(Blocks.CARROTS, blockRenderLayer2);
		map.put(Blocks.POTATOES, blockRenderLayer2);
		map.put(Blocks.COMPARATOR, blockRenderLayer2);
		map.put(Blocks.ACTIVATOR_RAIL, blockRenderLayer2);
		map.put(Blocks.IRON_TRAPDOOR, blockRenderLayer2);
		map.put(Blocks.SUNFLOWER, blockRenderLayer2);
		map.put(Blocks.LILAC, blockRenderLayer2);
		map.put(Blocks.ROSE_BUSH, blockRenderLayer2);
		map.put(Blocks.PEONY, blockRenderLayer2);
		map.put(Blocks.TALL_GRASS, blockRenderLayer2);
		map.put(Blocks.LARGE_FERN, blockRenderLayer2);
		map.put(Blocks.SPRUCE_DOOR, blockRenderLayer2);
		map.put(Blocks.BIRCH_DOOR, blockRenderLayer2);
		map.put(Blocks.JUNGLE_DOOR, blockRenderLayer2);
		map.put(Blocks.ACACIA_DOOR, blockRenderLayer2);
		map.put(Blocks.CHERRY_DOOR, blockRenderLayer2);
		map.put(Blocks.DARK_OAK_DOOR, blockRenderLayer2);
		map.put(Blocks.PALE_OAK_DOOR, blockRenderLayer2);
		map.put(Blocks.MANGROVE_DOOR, blockRenderLayer2);
		map.put(Blocks.BAMBOO_DOOR, blockRenderLayer2);
		map.put(Blocks.COPPER_DOOR, blockRenderLayer2);
		map.put(Blocks.EXPOSED_COPPER_DOOR, blockRenderLayer2);
		map.put(Blocks.WEATHERED_COPPER_DOOR, blockRenderLayer2);
		map.put(Blocks.OXIDIZED_COPPER_DOOR, blockRenderLayer2);
		map.put(Blocks.WAXED_COPPER_DOOR, blockRenderLayer2);
		map.put(Blocks.WAXED_EXPOSED_COPPER_DOOR, blockRenderLayer2);
		map.put(Blocks.WAXED_WEATHERED_COPPER_DOOR, blockRenderLayer2);
		map.put(Blocks.WAXED_OXIDIZED_COPPER_DOOR, blockRenderLayer2);
		map.put(Blocks.END_ROD, blockRenderLayer2);
		map.put(Blocks.CHORUS_PLANT, blockRenderLayer2);
		map.put(Blocks.CHORUS_FLOWER, blockRenderLayer2);
		map.put(Blocks.TORCHFLOWER, blockRenderLayer2);
		map.put(Blocks.TORCHFLOWER_CROP, blockRenderLayer2);
		map.put(Blocks.PITCHER_PLANT, blockRenderLayer2);
		map.put(Blocks.PITCHER_CROP, blockRenderLayer2);
		map.put(Blocks.BEETROOTS, blockRenderLayer2);
		map.put(Blocks.KELP, blockRenderLayer2);
		map.put(Blocks.KELP_PLANT, blockRenderLayer2);
		map.put(Blocks.TURTLE_EGG, blockRenderLayer2);
		map.put(Blocks.DEAD_TUBE_CORAL, blockRenderLayer2);
		map.put(Blocks.DEAD_BRAIN_CORAL, blockRenderLayer2);
		map.put(Blocks.DEAD_BUBBLE_CORAL, blockRenderLayer2);
		map.put(Blocks.DEAD_FIRE_CORAL, blockRenderLayer2);
		map.put(Blocks.DEAD_HORN_CORAL, blockRenderLayer2);
		map.put(Blocks.TUBE_CORAL, blockRenderLayer2);
		map.put(Blocks.BRAIN_CORAL, blockRenderLayer2);
		map.put(Blocks.BUBBLE_CORAL, blockRenderLayer2);
		map.put(Blocks.FIRE_CORAL, blockRenderLayer2);
		map.put(Blocks.HORN_CORAL, blockRenderLayer2);
		map.put(Blocks.DEAD_TUBE_CORAL_FAN, blockRenderLayer2);
		map.put(Blocks.DEAD_BRAIN_CORAL_FAN, blockRenderLayer2);
		map.put(Blocks.DEAD_BUBBLE_CORAL_FAN, blockRenderLayer2);
		map.put(Blocks.DEAD_FIRE_CORAL_FAN, blockRenderLayer2);
		map.put(Blocks.DEAD_HORN_CORAL_FAN, blockRenderLayer2);
		map.put(Blocks.TUBE_CORAL_FAN, blockRenderLayer2);
		map.put(Blocks.BRAIN_CORAL_FAN, blockRenderLayer2);
		map.put(Blocks.BUBBLE_CORAL_FAN, blockRenderLayer2);
		map.put(Blocks.FIRE_CORAL_FAN, blockRenderLayer2);
		map.put(Blocks.HORN_CORAL_FAN, blockRenderLayer2);
		map.put(Blocks.DEAD_TUBE_CORAL_WALL_FAN, blockRenderLayer2);
		map.put(Blocks.DEAD_BRAIN_CORAL_WALL_FAN, blockRenderLayer2);
		map.put(Blocks.DEAD_BUBBLE_CORAL_WALL_FAN, blockRenderLayer2);
		map.put(Blocks.DEAD_FIRE_CORAL_WALL_FAN, blockRenderLayer2);
		map.put(Blocks.DEAD_HORN_CORAL_WALL_FAN, blockRenderLayer2);
		map.put(Blocks.TUBE_CORAL_WALL_FAN, blockRenderLayer2);
		map.put(Blocks.BRAIN_CORAL_WALL_FAN, blockRenderLayer2);
		map.put(Blocks.BUBBLE_CORAL_WALL_FAN, blockRenderLayer2);
		map.put(Blocks.FIRE_CORAL_WALL_FAN, blockRenderLayer2);
		map.put(Blocks.HORN_CORAL_WALL_FAN, blockRenderLayer2);
		map.put(Blocks.SEA_PICKLE, blockRenderLayer2);
		map.put(Blocks.CONDUIT, blockRenderLayer2);
		map.put(Blocks.BAMBOO_SAPLING, blockRenderLayer2);
		map.put(Blocks.BAMBOO, blockRenderLayer2);
		map.put(Blocks.POTTED_BAMBOO, blockRenderLayer2);
		map.put(Blocks.SCAFFOLDING, blockRenderLayer2);
		map.put(Blocks.STONECUTTER, blockRenderLayer2);
		map.put(Blocks.LANTERN, blockRenderLayer2);
		map.put(Blocks.SOUL_LANTERN, blockRenderLayer2);
		Blocks.COPPER_LANTERNS.forEach(block -> map.put(block, blockRenderLayer2));
		map.put(Blocks.CAMPFIRE, blockRenderLayer2);
		map.put(Blocks.SOUL_CAMPFIRE, blockRenderLayer2);
		map.put(Blocks.SWEET_BERRY_BUSH, blockRenderLayer2);
		map.put(Blocks.WEEPING_VINES, blockRenderLayer2);
		map.put(Blocks.WEEPING_VINES_PLANT, blockRenderLayer2);
		map.put(Blocks.TWISTING_VINES, blockRenderLayer2);
		map.put(Blocks.TWISTING_VINES_PLANT, blockRenderLayer2);
		map.put(Blocks.NETHER_SPROUTS, blockRenderLayer2);
		map.put(Blocks.CRIMSON_FUNGUS, blockRenderLayer2);
		map.put(Blocks.WARPED_FUNGUS, blockRenderLayer2);
		map.put(Blocks.CRIMSON_ROOTS, blockRenderLayer2);
		map.put(Blocks.WARPED_ROOTS, blockRenderLayer2);
		map.put(Blocks.POTTED_CRIMSON_FUNGUS, blockRenderLayer2);
		map.put(Blocks.POTTED_WARPED_FUNGUS, blockRenderLayer2);
		map.put(Blocks.POTTED_CRIMSON_ROOTS, blockRenderLayer2);
		map.put(Blocks.POTTED_WARPED_ROOTS, blockRenderLayer2);
		map.put(Blocks.CRIMSON_DOOR, blockRenderLayer2);
		map.put(Blocks.WARPED_DOOR, blockRenderLayer2);
		map.put(Blocks.POINTED_DRIPSTONE, blockRenderLayer2);
		map.put(Blocks.SMALL_AMETHYST_BUD, blockRenderLayer2);
		map.put(Blocks.MEDIUM_AMETHYST_BUD, blockRenderLayer2);
		map.put(Blocks.LARGE_AMETHYST_BUD, blockRenderLayer2);
		map.put(Blocks.AMETHYST_CLUSTER, blockRenderLayer2);
		map.put(Blocks.CAVE_VINES, blockRenderLayer2);
		map.put(Blocks.CAVE_VINES_PLANT, blockRenderLayer2);
		map.put(Blocks.SPORE_BLOSSOM, blockRenderLayer2);
		map.put(Blocks.FLOWERING_AZALEA, blockRenderLayer2);
		map.put(Blocks.AZALEA, blockRenderLayer2);
		map.put(Blocks.PINK_PETALS, blockRenderLayer2);
		map.put(Blocks.WILDFLOWERS, blockRenderLayer2);
		map.put(Blocks.LEAF_LITTER, blockRenderLayer2);
		map.put(Blocks.BIG_DRIPLEAF, blockRenderLayer2);
		map.put(Blocks.BIG_DRIPLEAF_STEM, blockRenderLayer2);
		map.put(Blocks.SMALL_DRIPLEAF, blockRenderLayer2);
		map.put(Blocks.HANGING_ROOTS, blockRenderLayer2);
		map.put(Blocks.SCULK_SENSOR, blockRenderLayer2);
		map.put(Blocks.CALIBRATED_SCULK_SENSOR, blockRenderLayer2);
		map.put(Blocks.SCULK_VEIN, blockRenderLayer2);
		map.put(Blocks.SCULK_SHRIEKER, blockRenderLayer2);
		map.put(Blocks.MANGROVE_PROPAGULE, blockRenderLayer2);
		map.put(Blocks.FROGSPAWN, blockRenderLayer2);
		map.put(Blocks.COPPER_GRATE, blockRenderLayer2);
		map.put(Blocks.EXPOSED_COPPER_GRATE, blockRenderLayer2);
		map.put(Blocks.WEATHERED_COPPER_GRATE, blockRenderLayer2);
		map.put(Blocks.OXIDIZED_COPPER_GRATE, blockRenderLayer2);
		map.put(Blocks.WAXED_COPPER_GRATE, blockRenderLayer2);
		map.put(Blocks.WAXED_EXPOSED_COPPER_GRATE, blockRenderLayer2);
		map.put(Blocks.WAXED_WEATHERED_COPPER_GRATE, blockRenderLayer2);
		map.put(Blocks.WAXED_OXIDIZED_COPPER_GRATE, blockRenderLayer2);
		map.put(Blocks.FIREFLY_BUSH, blockRenderLayer2);
		map.put(Blocks.CACTUS_FLOWER, blockRenderLayer2);
		map.put(Blocks.BEACON, blockRenderLayer2);
		BlockRenderLayer blockRenderLayer3 = BlockRenderLayer.TRANSLUCENT;
		map.put(Blocks.ICE, blockRenderLayer3);
		map.put(Blocks.NETHER_PORTAL, blockRenderLayer3);
		map.put(Blocks.GLASS, blockRenderLayer3);
		map.put(Blocks.GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.WHITE_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.ORANGE_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.MAGENTA_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.LIGHT_BLUE_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.YELLOW_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.LIME_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.PINK_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.GRAY_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.LIGHT_GRAY_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.CYAN_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.PURPLE_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.BLUE_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.BROWN_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.GREEN_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.REDSTONE_WIRE, blockRenderLayer3);
		map.put(Blocks.RED_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.BLACK_STAINED_GLASS, blockRenderLayer3);
		map.put(Blocks.WHITE_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.ORANGE_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.MAGENTA_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.LIGHT_BLUE_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.YELLOW_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.LIME_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.PINK_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.GRAY_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.LIGHT_GRAY_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.CYAN_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.PURPLE_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.BLUE_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.BROWN_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.GREEN_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.RED_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.BLACK_STAINED_GLASS_PANE, blockRenderLayer3);
		map.put(Blocks.SLIME_BLOCK, blockRenderLayer3);
		map.put(Blocks.HONEY_BLOCK, blockRenderLayer3);
		map.put(Blocks.FROSTED_ICE, blockRenderLayer3);
		map.put(Blocks.BUBBLE_COLUMN, blockRenderLayer3);
		map.put(Blocks.TINTED_GLASS, blockRenderLayer3);
	});
	private static final Map<Fluid, BlockRenderLayer> FLUIDS = Util.make(Maps.<Fluid, BlockRenderLayer>newHashMap(), map -> {
		map.put(Fluids.FLOWING_WATER, BlockRenderLayer.TRANSLUCENT);
		map.put(Fluids.WATER, BlockRenderLayer.TRANSLUCENT);
	});
	private static boolean cutoutLeaves;

	public static BlockRenderLayer getBlockLayer(BlockState state) {
		Block block = state.getBlock();
		if (block instanceof LeavesBlock) {
			return cutoutLeaves ? BlockRenderLayer.CUTOUT : BlockRenderLayer.SOLID;
		} else {
			BlockRenderLayer blockRenderLayer = (BlockRenderLayer)BLOCKS.get(block);
			return blockRenderLayer != null ? blockRenderLayer : BlockRenderLayer.SOLID;
		}
	}

	public static RenderLayer getMovingBlockLayer(BlockState state) {
		Block block = state.getBlock();
		if (block instanceof LeavesBlock) {
			return cutoutLeaves ? RenderLayers.cutout() : RenderLayers.solid();
		} else {
			BlockRenderLayer blockRenderLayer = (BlockRenderLayer)BLOCKS.get(block);
			if (blockRenderLayer != null) {
				return switch (blockRenderLayer) {
					case SOLID -> RenderLayers.solid();
					case CUTOUT -> RenderLayers.cutout();
					case TRANSLUCENT -> RenderLayers.translucentMovingBlock();
					case TRIPWIRE -> RenderLayers.tripwire();
				};
			} else {
				return RenderLayers.solid();
			}
		}
	}

	public static RenderLayer getEntityBlockLayer(BlockState state) {
		BlockRenderLayer blockRenderLayer = getBlockLayer(state);
		return blockRenderLayer == BlockRenderLayer.TRANSLUCENT ? TexturedRenderLayers.getBlockTranslucentCull() : TexturedRenderLayers.getEntityCutout();
	}

	public static BlockRenderLayer getFluidLayer(FluidState state) {
		BlockRenderLayer blockRenderLayer = (BlockRenderLayer)FLUIDS.get(state.getFluid());
		return blockRenderLayer != null ? blockRenderLayer : BlockRenderLayer.SOLID;
	}

	public static void setCutoutLeaves(boolean cutoutLeaves) {
		BlockRenderLayers.cutoutLeaves = cutoutLeaves;
	}
}
